AWSTemplateFormatVersion: 2010-09-09
Description: "Cloud Launchpad: VPC + EC2 - beginner-friendly reStart lab template."

Parameters:
  ProjectName:
    Type: String
    Default: cloud-launchpad
    Description: "Used in Name tags to make resources easy to find."
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues: [t3.micro, t2.micro]
    Description: "EC2 size (lab default is t3.micro)."
  LatestAmazonLinuxAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: "SSM path for the latest Amazon Linux 2 AMI."

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpc"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-igw"

  AttachIgw:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-private-subnet"

  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH from anywhere (lab) and all egress"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-sg"

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet
      ImageId: !Ref LatestAmazonLinuxAMI
      SecurityGroupIds: [!Ref InstanceSG]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-ec2"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Welcome to ${ProjectName} (private subnet)" | tee /etc/motd

Outputs:
  VpcId:
    Description: "VPC ID"
    Value: !Ref VPC
  PrivateSubnetId:
    Description: "Private Subnet ID"
    Value: !Ref PrivateSubnet
  SecurityGroupId:
    Description: "Security Group ID"
    Value: !Ref InstanceSG
  InstanceId:
    Description: "EC2 Instance ID"
    Value: !Ref Instance
